### ISSUE TITLE
Not able to access ompss2 examples

### ISSUE THREAD

**Issue by miniskar** [bsc-pm/ompss-2-cluster-releases#1]
Hi, 
I am trying to access ompss2 examples. However, I am not able to access them. 
https://pm.bsc.es/gitlab/ompss-2/examples

Can you make it available in github.com?

With Regards,
Narasinga.

**Comment by kevinsala** [comment]
Hi Narasinga,
Currently, there is a technical issue in our internal GitLab. They're working on recovering it (hopely soon). I'll let you know once our GitLab is back online.

Sorry for the inconvenience,
Kevin

**Comment by kevinsala** [comment]
Hi Narasinga,

The issue has been solved and our GitLab is back online: https://pm.bsc.es/gitlab/ompss-2/examples

Kind regards,
Kevin Sala

**Comment by miniskar** [comment]
Thank you.
